### ISSUE TITLE
Implementazione Preprocessing

### ISSUE THREAD

**Issue by tonca** [tonca/datamining_project#1]
Ho inserito una classe statica [PropertyFilters](https://github.com/tonca/datamining_project/blob/master/src/main/java/it/unipd/dei/dm1617/death_mining/PropertyFilters.java) per le funzioni di filtraggio delle transazioni.
Mi sembra una buona soluzione per organizzare la cosa, così potranno essere utilizzate anche da eventuali altre classi, tipo se implementiamo a-priori. 
Eventualmente si può anche fare una funzione che prende in input tutta la lista di item, invece del singolo item, questo darebbe più possibilità di fondere campi o cose del genere.

A questo punto andrebbero implementati i vari filtri. 

> In realtà volevo soprattutto testare gli issues ;)

**Comment by tonca** [comment]
Ho caricato la classe [Analytics](https://github.com/tonca/datamining_project/blob/master/src/main/java/it/unipd/dei/dm1617/death_mining/Analytics.java). Calcola il supporto d ogni item e carica i risultati nella cartella `/results/stats`.

**Comment by tonca** [comment]
Abbiamo bisogno di eseguire le operazioni seguenti:
- Selezione di entrate, sia secondo la colonna che secondo il valore
- Binning di feature differente da quelli già presenti (es. Age e Cause)
- Fusione di colonne (es. Education1989 + Education2003)

Per fare ciò è necessaria un metodo statico che prende in input gli itemset, invece dei valori singoli, come fa attualmente `PropertyFilters.reject()`

**Comment by martinid94** [comment]
Alcune considerazioni:

1. Osservando gli output (sia di lift che di convinction) direi che i risultati sono sensati e abbastanza puliti (si considerano quelli ottenuti con il metodo rejectUselessAndFrequent() di PropertyFilters). Aspetto vostri pareri ;)
2. Al momento ho considerato AgeRecode3, Edication2003Revision e RaceRecode3 (un binning di Race) per i test. Quando saranno disponibili il binning di Age e la colonna Education, si dovrà modificare leggermente il codice di ProperyFilters.  
3. Negli output spesso si trovano itemsets e regole che coinvolgono NumberOfEntityAxisConditions e NumberOfRecordAxisConditions. Sono colonne rilevanti? Cosa rappresentano? Conviene fare un "rename" di tali colonne?
4. La distinzione dei metodi rejectUseless() e rejectUselessAndFrequent() di PropertyFilters è motivata dal fatto che il secondo può essere realizzato solo dopo una computazione e un' analisi degli output, mentre il primo è stato costruito con la conoscenza "a priori" del dataset. Averli distinti specifica meglio il processo di filtraggio seguito.
5. I metodi rejectAdditionalColumns() e rejectAdditionalValues() di PropertyFilters sono solamente funzionalità di comodo. In particolare possono essere utili per il calcolo (o per verificare l'esistenza) di regole associative tra particolari colonne e/o valori.
