### ISSUE TITLE
Implementazione Conviction

### ISSUE THREAD

**Issue by marcusNet** [tonca/datamining_project#3]
La metrica Conviction può essere implementata in modo analogo a quello proposto con la metrica lift (Classe testLift) ma rimane da risolvere il problema del calcolo del **supporto di X unito ad Y negato**, parametro fondamentale per calcolare la conviction.

**Comment by geeanlooca** [comment]
Su [Wikipedia](https://en.wikipedia.org/wiki/Association_rule_learning#Useful_Concepts) la conviction è definita in un modo diverso da quello visto in classe e (credo) molto più facile da implementare. Applicando la formula agli esempi sulle slide si ottengono gli stessi risultati quindi sembra sia lecito usare questa definizione.

**Comment by geeanlooca** [comment]
Ho implementato la conviction definita come nel post precedente, quindi direi che si può chiudere l'issue.
