### ISSUE TITLE
Test nuova implementazione lift

### ISSUE THREAD

**Issue by geeanlooca** [tonca/datamining_project#4]
Ho sperimentato un po' con il metodo `join()` per calcolare le nuove metriche dato che Ceccarello l'aveva suggerito. Per ora il lift viene calcolato facendo una ricerca sulla lista di frequent itemset calcolata da FPGrowth, ma questa non è distribuita sui vari core/worker. La nuova implementazione dovrebbe essere più efficiente, anche se nel nostro caso non dovrebbe cambiare così tanto in termini di tempo di esecuzione. Se qualcuno che ha già analizzato i risultati calcolati col metodo precedente può verificare che quelli generati col nuovo metodo siano consistenti mi farebbe un gran favore.

**Comment by tonca** [comment]
Qua ci sono gli output ordinati per lift dei due metodi. 
L'ordine è lo stesso, ma i valori del lift sono leggermente diversi (tipo dell'ordine del 10^(-3)).
[LiftTest.txt](https://github.com/tonca/datamining_project/files/1018834/LiftTest.txt)
[JoinTest.txt](https://github.com/tonca/datamining_project/files/1018835/JoinTest.txt)

**Comment by geeanlooca** [comment]
penso che le lievi differenze siano dovute al sampling

**Comment by tonca** [comment]
Giusto! Si, chiaro.
