### ISSUE TITLE
Proposta nuove metriche

### ISSUE THREAD

**Issue by geeanlooca** [tonca/datamining_project#6]
Ho trovato questo [mini-tutorial](http://michael.hahsler.net/research/association_rules/measures.html) online dove vengono spiegate delle metriche di interesse per i frequent itemset e le regole associative che non abbiamo visto a lezione. Potrebbe essere interessante implementarne qualcuna se non ci porta via troppo tempo.

**Comment by tonca** [comment]
Sono mille! 
Sì secondo me è una buona idea, anche se forse rischia di diventare difficile da inserire nel rapporto. 
Ci salta fuori una matriciona della Madonna, anche aggiungendone solo un paio...
