### ISSUE TITLE
Organizzazione lavoro

### ISSUE THREAD

**Issue by arcticriki** [tonca/datamining_project#7]
- ~~Merge delle varie metriche~~: @geeanlooca;
- Scaletta report e divisione scrittura sezioni;
- ~~Export dei risultati~~
- Script per automatizzare compilazione e run

**Comment by geeanlooca** [comment]
Ho aggiunto la possibilità di salvare le regole trovate e gli itemset in formato CSV. I risultati vengono salvati in una cartella dentro a `/results` con data e ora come nome. Per ora non ho applicato filtraggi vari sulle varie metriche, se necessitate ditemelo pure.

**Comment by geeanlooca** [comment]
@arcticriki ti ho aggiunto il supporto della regola nell'output :) 57d543a497d65056401fe67b8e9385222fe36902
