### ISSUE TITLE
Selezioni sottogruppi

### ISSUE THREAD

**Issue by tonca** [tonca/datamining_project#8]
Sarà necessario un metodo per filtrare gli itemset in relazione a dei valori specificabili (e.g Sex = M, Age=Old) 
Considerare la possibilità di riselezionare eventuali rebinning o filtri.

**Comment by tonca** [comment]
Raga scusate, l'ho fatto io. :/ Alla fine erano davvero due righe e avevo troppa voglia di vedere i risultati.

Ma ci sarebbero ancora alcune cose da valutare.
Nello specifico bisogna decidere se togliere o meno le categorie troppo frequenti.
Per ogni sottogruppo, infatti, sono diverse (es. i bambini morti sotto i 5 anni non erano sposati. O_O ) e si potrebbero filtrare automaticamente basandosi sull'output della classe `Analytics`, ma bisognerebbe formalizzare le motivazioni della cosa e io chiederei prima al prof se è giustificabile.

**Comment by geeanlooca** [comment]
@arcticriki ti ho aggiunto il supporto della regola nell'output :) 57d543a497d65056401fe67b8e9385222fe36902
