### ISSUE TITLE
Binning Education Property

### ISSUE THREAD

**Issue by arcticriki** [tonca/datamining_project#9]
Il binning della property education è errato. 
Il file in uscita da Analytics riscontra valori sbagliati:

![image](https://cloud.githubusercontent.com/assets/26539795/26411741/efb7c644-40a6-11e7-9497-0a8351d74663.png)

Come vedete, le probabilità non sommano ad 1.

**Comment by tonca** [comment]
Si confermo, cercherò di trovare una soluzione.
